backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use backend\models\VProgram;
use backend\models\Pipeline;
use backend\models\VProject;
use backend\models\Queries;
use backend\models\DashboardSearch;
use backend\models\Innovator;
use backend\models\VDelayedMilestone;
use yii\filters\AccessControl;
use yii\web\Controller;
use common\models\LoginForm;
use yii\filters\VerbFilter;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index','milestones','choosepipeline','widget'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                    'milestones' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }
	 public function actionWidget($widget,$location) {
		 return $this->renderAjax('widget',['location'=>$location,'widget'=>$widget]);
	 }
    public function actionMilestones(){
        $data = Yii::$app->request->post();
        $sql_delayed ='SELECT a.timeline,a.milestone,a.expected_finish_date
                    FROM v_delayed_milestone a
                    WHERE finish_date is null
                    AND a.project_id='.$data['project_id'].'
				    AND date(a.expected_finish_date)	<= date\''.date('Y-m-d').'\'	  
						  ';
        $delayed_milestones = Yii::$app->db->createCommand($sql_delayed)->queryAll();
        return json_encode($delayed_milestones);
    }

    public function actionIndex()
    { 

		 $session = Yii::$app->session;
		 if(isset($_REQUEST['pipeline'])) {
			 $o=Pipeline::findOne(['id'=>$_REQUEST['pipeline']]);
			 if($o) {
				 $session->set('pipeline',$_REQUEST['pipeline']);
				 $session->set('pipeline_a',$o);
			 }
			 else
				$session->remove('pipeline'); 
		 }

		 if($this->getPrograms() > 0) {
         if($this->getProjects()==0){
         return $this->render('projects');
          }

        return $this->render('index',
                    ['programs'                => $this->getPrograms(),
                    'innovators'               => $this->getInnovators(),
                    'projects'                 => $this->getProjects(),
                    'pipelines'                => $this->getPipelines(),
                    'delayed_milestone_count'  => count(Yii::$app->db->createCommand(Queries::qryOverDue())->queryAll())
                    ]);
		} else {  //No portfolios. render Welcome Page

			return $this->render('welcome');
		}
    }    
   
    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $this->layout = '@common/themes/AdminLTE/views/layouts/login.php';
        
        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('@common/themes/AdminLTE/views/site/login.php', [
                'model' => $model,
                'form_title'=>'Admin Login'
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout(); 
        return $this->goHome();
    }

    //HELPER FUNCTIONS FOR DASHBOARD

    private function getPrograms(){
        return VProgram::find()->where(['pipeline_id'=>Yii::$app->session['pipeline'],'institution_id' => Yii::$app->user->identity->institution])->count();
    }

    private function getProjects(){
        return VProject::find()->where(['pipeline_id'=>Yii::$app->session['pipeline'],'institution' => Yii::$app->user->identity->institution])->count();
    }
    private function getPipelines(){
        return Pipeline::find()->count();
    }
    private function getInnovators(){
        return VProject::find()->select('innovator')->where(['pipeline_id'=>Yii::$app->session['pipeline'],'institution' => Yii::$app->user->identity->institution])->distinct()->count();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use frontend\models\VProgram;
use frontend\models\Project;
use frontend\models\LoginInnovator;
use frontend\models\Pipeline;
use frontend\models\VProject;
use frontend\models\Queries;
use frontend\models\DashboardSearch;
use frontend\models\Innovator;
use frontend\models\VDelayedMilestone;
use yii\filters\AccessControl;
use yii\web\Controller;
use common\models\LoginForm;
use yii\filters\VerbFilter;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index','milestones','choosepipeline'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                    'milestones' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }
    public function actionMilestones(){
        $data = Yii::$app->request->post();
        $sql_delayed ='SELECT a.timeline,a.milestone,a.expected_finish_date
                    FROM v_delayed_milestone a
                    WHERE finish_date is null
                    AND a.project_id='.$data['project_id'].'
				    AND date(a.expected_finish_date)	<= date\''.date('Y-m-d').'\'	  
						  ';
        $delayed_milestones = Yii::$app->db->createCommand($sql_delayed)->queryAll();
        return json_encode($delayed_milestones);
    }

    public function actionIndex()
    { 
        //$delayed_milestones = VDelayedMilestone::find()->where(['submission_date'=>0])->all();
        $project                        = Project::findOne(['innovator'=>Yii::$app->user->identity->innovator])->id;
        if(!$project){
            return $this->render('welcome');
        }

        $team_members                   = LoginInnovator::find()->where(['innovator'=>Yii::$app->user->identity->innovator])->all();
        $team_count                     = count($team_members);

        $delayed_milestones             = Yii::$app->db->createCommand(Queries::qryDelayed($project))->queryAll();
        $approved_milestones            = Yii::$app->db->createCommand(Queries::SQLApproved($project))->queryAll();
        $rejected_milestones            = Yii::$app->db->createCommand(Queries::SQLRejected($project))->queryAll();
        $qry_iteration                  = Yii::$app->db->createCommand(Queries::qryIteration($project))->queryAll();
        $delayed_milestone_count        = count($delayed_milestones);
        $approved_milestone_count       = count($approved_milestones);
        $rejected_milestone_count       = count($rejected_milestones);

        
        return $this->render('index', [
            'innovators'                => $this->getInnovators(),
            'projects'                  => $this->getProjects(),
            'pipelines'                 => $this->getPipelines(),
            'delayed_milestones'        => $delayed_milestones,
            'team_count'                => $team_count,
            'project'                   => $project,
            'delayed_milestone_count'   => $delayed_milestone_count,
            'rejected_milestones'       => $rejected_milestones,
            'approved_milestones'       => $approved_milestones,
            'rejected_milestone_count'  => $rejected_milestone_count,
            'approved_milestone_count'  => $approved_milestone_count
        ]);
    }    
   
    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $this->layout = '@common/themes/AdminLTE/views/layouts/login.php';
        
        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('@common/themes/AdminLTE/views/site/login.php', [
                'model' => $model,
                'form_title'=>'Project Login'
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout(); 
        return $this->goHome();
    }

     //HELPER FUNCTIONS FOR DASHBOARD

    private function getProjects(){
        return Project::find()->where(['innovator'=>Yii::$app->user->identity->innovator])->count();
    }
    private function getPipelines(){
        return Pipeline::find()->count();
    }
    private function getInnovators(){
        return Innovator::find()->count();
    }
}

backend/views/site/choosepipeline.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">
	<?php print_r($_SERVER);?>
    <h1><?= Html::encode($this->title) ?></h1>
    <p>Please select a pipeline</p>
    <p></p>
</div>

backend/views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<section class="content">

    <div class="error-page">
        <h2 class="headline text-info"><i class="fa fa-warning text-yellow"></i></h2>

        <div class="error-content">
            <h3><?= $name ?></h3>

            <p>
                <?= nl2br(Html::encode($message)) ?>
            </p>

            <p>
                The above error occurred while the Web server was processing your request.
                Please contact us if you think this is a server error. Thank you.
                Meanwhile, you may <a href='<?= Yii::$app->homeUrl ?>'>return to dashboard</a>.
            </p>

            <!--<form class='search-form'>
                <div class='input-group'>
                    <input type="text" name="search" class='form-control' placeholder="Search"/>

                    <div class="input-group-btn">
                        <button type="submit" name="submit" class="btn btn-primary"><i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>-->
        </div>
    </div>

</section>

backend/views/site/index.php
<?php
use yii\grid\GridView;
use yii\helpers\Url;
/* @var $this yii\web\View */

$asset          = common\assets\HighStockAsset::register($this);
$baseUrl        = $asset->baseUrl;

$this->title = Yii::$app->session['pipeline_a']['name']. " Dashboard";
//print_r(Yii::$app->session['pipeline_a']);
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="site-index">
    <!-- Info boxes -->
    <div class="row">
        <div class="col-lg-3 col-xs-12">
            <!-- small box -->
            <div class="small-box bg-aqua">
                <div class="inner">
                    <h3><?=$programs?></h3>
                    <p>No. of Portfolios</p>
                </div>
                <div class="icon">
                    <i class="fa fa-object-group"></i>
                </div>
                <a href="<?= Url::to(['/program']);?>" class="small-box-footer">Portfolios <span class="fa fa-arrow-circle-right"></span></a>
            </div>
        </div>
        <div class="col-lg-3 col-xs-12">
            <!-- small box -->
            <div class="small-box bg-red">
                <div class="inner">
                    <h3><?=$delayed_milestone_count?></h3>
                    <p>No. of Overdue Projects</p>
                </div>
                <div class="icon">
                    <i class="fa fa-file-text-o"></i>
                </div>
                <a href="#overdue_projects" class="small-box-footer">View Overdue Projects <span class="fa fa-arrow-circle-right"></span></a>
            </div>
        </div>

        <!-- fix for small devices only -->
        <div class="clearfix visible-sm-block"></div>
        <div class="col-lg-3 col-xs-12">
            <!-- small box -->
            <div class="small-box bg-green">
                <div class="inner">
                    <h3><?=$innovators?></h3>
                    <p>No. of Project Teams</p>
                </div>
                <div class="icon">
                    <i class="fa fa-user"></i>
                </div>
                <a href="<?= Url::to(['/innovator']);?>" class="small-box-footer">Project Teams <span class="fa fa-arrow-circle-right"></span></a>
            </div>
        </div>
        <div class="col-lg-3 col-xs-12">
            <!-- small box -->
            <div class="small-box bg-yellow">
                <div class="inner">
                    <h3><?=$projects?></h3>
                    <p>No. of Projects</p>
                </div>
                <div class="icon">
                    <i class="fa fa-file-text-o"></i>
                </div>
                <a href="<?= Url::to(['/project']);?>" class="small-box-footer">Projects <span class="fa fa-arrow-circle-right"></span></a>
            </div>
        </div>
    </div><!-- /.row -->
    <div class="row">
        <div class="col-md-6">
            <div class="box box-success">
                <div class="box-body ">
<a class="btn btn-xs btn-default modalButton" href="<?=Url::to(['/site/widget','widget'=>'MilestonesAchieved','location'=>'backend'])?>" title="Open in a New Window"><i class="glyphicon glyphicon-new-window"></i></a>  <button id="button">Hide Projects</button>                  <?php  $s= '\backend\components\MilestonesAchieved';
						 echo $s::widget(['element_id'=>'milestones_achieved']) ?> 

                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="box box-success">
                <div class="box-body ">
						 <a class="btn btn-xs btn-default modalButton" href="<?=Url::to(['/site/widget','widget'=>'CummulativeScore2','location'=>'common'])?>" title="Open in a New Window"><i class="glyphicon glyphicon-new-window"></i></a>
                 <?= \common\components\CummulativeScore2::widget() ?>   
                </div>
            </div>
        </div>
    </div>
    <div class="row">
                <div class="col-lg-6">
            <div class="box box-success">
                <div class="box-body ">
						 <a class="btn btn-xs btn-default modalButton" href="<?=Url::to(['/site/widget','widget'=>'MilestoneSubmission','location'=>'backend'])?>" title="Open in a New Window"><i class="glyphicon glyphicon-new-window"></i></a>
                    <?= \backend\components\MilestoneSubmission::widget() ?>  
                </div>
            </div>
        </div>
                <div class="col-lg-6">
            <div class="box box-success">
                <div class="box-body ">
						 <a class="btn btn-xs btn-default modalButton" href="<?=Url::to(['/site/widget','widget'=>'MilestoneSubmission2','location'=>'backend'])?>" title="Open in a New Window"><i class="glyphicon glyphicon-new-window"></i></a>
                    <?= \backend\components\MilestoneSubmission2::widget() ?>  
                </div>
            </div>
        </div>
		  
    </div>
   <div class="row">
               <div class="col-lg-6">
           <div class="box box-success">
               <div class="box-body ">
					 <a class="btn btn-xs btn-default modalButton" href="<?=Url::to(['/site/widget','widget'=>'MilestoneDelays','location'=>'backend'])?>" title="Open in a New Window"><i class="glyphicon glyphicon-new-window"></i></a>
					 
                   <?= \backend\components\MilestoneDelays::widget() ?>  
               </div>
           </div>
       </div>
               <div class="col-lg-6">
           <div class="box box-success">
               <div class="box-body ">
			  		<select id=cummind>
						<?php
					 //  $s=$this->portfolio ? "portfolio_id=".$this->portfolio : "pipeline_id=".Yii::$app->session['pipeline'];
					 	$qry_cummulative = Yii::$app->db->createCommand("SELECT DISTINCT indicator_id,indicator_name FROM `v_indicator_milestone_submission` WHERE pipeline_id=".Yii::$app->session['pipeline'])->queryAll();
						foreach($qry_cummulative as $s)
							echo "<option value=".$s[indicator_id].">".$s[indicator_name]."</option>";
						?>
					</select>
					<a class="btn btn-xs btn-default modalButton" href="<?=Url::to(['/site/widget','widget'=>'CummulativeScoreIndicators','location'=>'common'])?>" title="Open in a New Window"><i class="glyphicon glyphicon-new-window"></i></a>
			                   <?= \common\components\CummulativeScoreIndicators::widget() ?>
					
               </div>
           </div>
       </div>
   </div>
	
      <div class="row" id="overdue_projects">
<?php // \backend\components\OverdueProject::widget() ?>
<?php // \backend\components\ProjectProgress::widget() ?>
    </div>
<?php // \backend\components\LateSubmission::widget() ?>


</div>
<style>
#editModalId 
{
    width: 96%; 
} 

#editModalId .modal-body {
    max-height: 100%;
	 max-width: 1200px;
}
</style>
<?php
yii\bootstrap\Modal::begin([
		'header' => '',
		'id'=>'editModalId',
		'class' =>'modal',
		'size' => 'modal-lg',
]);
echo "<div class='modalContent' ></div>";
yii\bootstrap\Modal::end();
$this->registerJsFile(Url::to(['/js/modal.js']), [
    'depends'=>\yii\web\JqueryAsset::className()
]);
?>

<!-- Page specific script -->
<?= $this->registerJs(
    " 
    function dateToYMD(date) {
    var d = date.getDate();
    var m = date.getMonth() + 1;
    var y = date.getFullYear();
    return '' + y + '-' + (m<=9 ? '0' + m : m) + '-' + (d <= 9 ? '0' + d : d);
    }

  $('#dashboard_nav').addClass('active');
  $('.load_milestone').click(function(){
  $('#milestone_header').html('Loading Milestones');
  $('.menu-milestone').html('');
  $('.overlay').show();
  var project_id = $(this).attr('id');
  $.ajax({
          method: 'POST',
          url: 'site/milestones/',
          data: { project_id: project_id },
          dataType:'JSON'
        })
    .done(function(response) {
    $('#milestone_header').html('Overdue Milestones');
    $('.overlay').hide();
    $.each(response, function( index, value ) {
       $('.menu-milestone').append('<tr><th class=\"col-md-8\"><a href=\"project/timeline-entry/'+value.timeline+'\">'+value.milestone+'</a></th><th class=\"col-md-4\"><span>Due on '+dateToYMD(new Date(value.expected_finish_date))+' </span></th>');    });
    });
})

      /**
 * This is an advanced demo of setting up Highcharts with the flags feature borrowed from Highstock.
 * It also shows custom graphics drawn in the chart area on chart load.
 */

")
?>

backend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
Use yii\helpers\Url;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>

<link href="<?=Url::base()?>/css/style.css" rel="stylesheet" type="text/css" media="all"/>

<div class="login-main">
    <div class="login"> <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>
        <div class="social">
            <ul>
                <li class="last-mar"><a class="loginicon" href="#">Admin Login</a></li>
            </ul>
        </div>
        <?= $form->field($model, 'email',
            ['options'=>[
                'tag'=>'div',
                'class'=>'form-group field-loginform-usernasme has-feedback required'],
                'template'=>'{input}<span class="glyphicon glyphicon-user form-control-feedback" style="color:#00a65a"></span>{error}{hint}'
            ])->textInput(['placeholder'=>'Email',]) ?>
        <?= $form->field($model, 'password',['options'=>[
            'tag'=>'div',
            'class'=>'form-group field-loginform-password has-feedback required'],
            'template'=>'{input}<span class="glyphicon glyphicon-lock form-control-feedback" style="color:#00a65a"></span>{error}{hint}'
        ])->passwordInput(['placeholder'=>'Password']) ?>
        <ul class="button">
            <li><input type="submit" value="Submit" ></li>
            <li><input class="clear" type="Reset" value="Clear"></li>
        </ul>
        <!--
		<div class="forgot">
           <?= $form->field($model, 'rememberMe',['options'=>[
            'tag'=>'div',
            'class'=>'form-group field-loginform-rememberme'],
        ])->checkbox() ?>
	   	  <div class="forgot-para">
	   	  	<a href="#"> <p>Forgot Your Password?</p></a>
	   	  </div>
	   	<div class="clear"> </div>
	   </div>-->
    </div><?php ActiveForm::end(); ?>
    <div class="login-password">
        <p>Dynamic Project Trajectory Tracking Toolkit</p>
    </div>
</div>
<div class="copyright">
    <p>&copy; 2016 <a href="#" target="_blank">DPTTT</a></p>
</div>

backend/views/site/myview.php
The message is:  
<?php echo $message; ?>

backend/views/site/projects.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
$this->title = "Welcome to DPTT";
//print_r(Yii::$app->session['pipeline_a']);
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="site-index">
<div class="box box-success">
<div class="box-header bg-success with-border">
                  <h3 class="box-title">This Pipeline has no projects. You can create a project by using the link below</h3>
            </div>
            <div class="box-body">
            <div style="text-align:center ">
            	 <?= Html::a("<i class=\"fa fa-map-o\"></i> Create a Project", ['/project/create'],['class'=>'btn btn-lg btn-success']) ?> 
            	 </div>
            </div>
 </div>
 </div>

backend/views/site/welcome.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
$this->title = "Welcome to DPTT";
//print_r(Yii::$app->session['pipeline_a']);
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="site-index">
<div class="box box-success">
<div class="box-header bg-success with-border">
                  <h3 class="box-title">This Pipeline has no Portfolio. Create a Portfolio and start assigning Projects to it</h3>
            </div>
            <div class="box-body">
            <div style="text-align:center ">
            	 <?= Html::a("<i class=\"fa fa-map-o\"></i> Create a Portfolio", ['/program/create'],['class'=>'btn btn-lg btn-success']) ?> 
            	 </div>
            </div>
 </div>
 </div>

backend/views/site/widget.php
<?php
use yii\grid\GridView;
use yii\helpers\Url;
/* @var $this yii\web\View */

$asset          = common\assets\HighStockAsset::register($this);
$baseUrl        = $asset->baseUrl;
$f="\\".$location."\components\\".$widget;
	if (Yii::$app->request->isAjax) { 
		?>
		<style>
		.xlarge {
			width:1000px !important;
			height:800px !important;
		}
		</style>
		<?php 
	 }
	// $params['elementid']=$widget.$location;
//	die(print_r($_REQUEST));
?>
        <div class="col-md-6">
            <div class="box box-success">
                <div class="box-body ">
<?=$f::widget($_REQUEST['params'])?>
                </div>
            </div>
        </div>