backend/controllers/ProjectController.php
<?php

namespace backend\controllers;

use backend\models\DurationUnit;
use backend\models\VPipeline;
use backend\models\Rawdata;
use Yii;
use backend\models\Project;
use backend\models\VProject;
use backend\models\Indicator;
use backend\models\ProjectSearch;
use backend\models\Timeline;
use backend\models\TimelineSearch;
use backend\models\TimelineForm;
use backend\models\Iteration;
use backend\models\IterationSearch;
use backend\models\Milestone;
use common\models\Functions;
use backend\models\MilestoneSubmission;
use backend\models\ExtensionRequests;
use backend\models\ExtensionRequestsSearch;
use backend\models\Attachments;
use backend\models\MilestoneSub;
use backend\models\Pipeline;
use backend\models\Program;
use backend\models\VMilestoneStage;
use backend\models\VPipelineStage;
use backend\models\VIndicatorSubmission;
use backend\models\VMilestoneSubmission;
use backend\models\IndicatorMilestone;
use backend\models\VStaticIndicatorMilestone;
use backend\models\Innovator;
use backend\models\Queries;
use app\models\Notification;
use yii\db\Expression;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\base\Action;
use yii\base\Model;
use yii\bootstrap\ActiveForm;
use yii\web\Response;
use yii\grid\GridView;
use yii\helpers\Html;
use backend\models\IndicatorMilestoneSubmission;
use backend\models\IndicatorMilestoneSubmissionSearch;
use backend\models\IndicatorMilestoneSubSearch;
use backend\models\Grading;
use backend\models\LoginInnovator;
use yii\web\ForbiddenHttpException;
use backend\models\UserForm;
use backend\models\Outcome;
use backend\models\Output;
use backend\models\Stage;
use backend\models\PipelineStage;
use backend\models\MilestoneStage;
use common\models\ProjectIndicatorWeight;
use backend\models\LogicalAttribute;
use backend\models\IntervalUnitMap;
use backend\models\IndicatorGrades;
use backend\models\PipelineIndicatorweight;
/**
 * ProjectController implements the CRUD actions for Project model.
 */
class ProjectController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }
 
	 public function actionGradet() {
		 echo "<table border=1>";
		 for($i=59;$i<101;$i++) {
		 $grade=0;
		 echo $i." ";
		 $d=Yii::$app->db->createCommand("SELECT * from v_milestone_submission where  project_id =".$i." order by created_at asc")->queryAll();
		 foreach($d as $dd) {
			 $ddate=date_format(date_add(date_create($dd['start_date']),date_interval_create_from_date_string($dd['duration']." days")),"Y-m-d");
			 $grade = round(@((strtotime($ddate) - strtotime($dd['start_date']))/(strtotime($dd['end_date']) - strtotime($dd['start_date']))),5);
			 Yii::$app->db->createCommand("update grading set grade='".$grade."' where milestone_submission=".$dd['id'])->execute();
			 echo "<tr><td>".$dd['start_date']."</td><td>".$dd['duration']."</td><td>".$ddate."</td><td>".$dd['end_date']."</td><td>".$grade."</td></tr>";
		 }
		 		 echo "</table>";
		}
	 }

	 public function actionCreatemilestones() {
		 $dates=Yii::$app->db->createCommand("select distinct podate from rawdata order by podate asc")->queryAll();
		 $indicators=[104,105,106,107];
		 $stage=46;
		 for($i=0;$i<count($dates);$i++) {
			 $name=$dates[$i]['podate'];
			 $ms=Milestone::find()->where(['milestone'=>$name])->one();
			 if(!$ms) {
				 $ms=new Milestone;
				 $ms->milestone=$name;
				 $ms->num=$i;
				 $ms->description="Milestone for orders on the date: ".$dates[$i]['podate'];
				 $ms->save() or die(print_r($ms->getErrors()));
			 }
			 $mst=MilestoneStage::find()->where(['milestone'=>$ms->id,'stage'=>$stage])->one();
			 if(!$mst) {
			 	  $mst=new MilestoneStage;
				  $mst->milestone=$ms->id;
				  $mst->stage=$stage;
				  $mst->ordering=$i;
				  $mst->weight=1;
				  $mst->save() or die(print_r($mst->getErrors()));
			 }
			 foreach($indicators as $in) {
				 $ii=PipelineIndicatorweight::find()->where(['indicator'=>$in,'milestone'=>$ms->id,'stage'=>$stage,'pipeline'=>30])->one();
				 if(!$ii) {
					 $ii=new PipelineIndicatorweight;
					 $ii->indicator=$in;
					 $ii->milestone=$ms->id;
					 $ii->stage=$stag;
					 $ii->pipeline=30;
					 $ii->weight=1;
					 $ii->save() or die(print_r($ii->getErrors()));;
				 }
			 }
		 }
	 	
	 }
	 
	 public function actionLogical() {
		 
		 $in[108]=[957=>41,958=>82,959=>86,960=>76,961=>87,962=>78,963=>77,964=>86,965=>87,966=>85,967=>86,968=>90];
		 $in[109]=[969=>3,970=>9,971=>5];
		 $in[110]=[969=>25,970=>20,971=>23];
		 $in[111]=[972=>8,973=>30.3,974=>45.2,975=>56.1,976=>57.1,977=>23,978=>67,979=>69,980=>58,981=>52,982=>56,983=>65];
		 $in[112]=[972=>99.45,973=>98.9,974=>99.9,975=>99.9,976=>99.9,977=>99.6,978=>99.8,979=>100,980=>100,981=>99.8,982=>100,983=>99.9];
		 $in[113]=[972=>98.86,973=>99.9,974=>99.9,975=>99.9,976=>98.7,977=>99.4,978=>99.3,979=>99.9,980=>100,981=>99.3,982=>99.1,983=>99.6];
	
  		$sta[47]=[108=>$in[108]];
  		$sta[48]=[109=>$in[109],110=>$in[110]];
  		$sta[49]=[111=>$in[111],112=>$in[112],113=>$in[113]];
		 
		 $tmln=Timeline::find()->where(['project'=>101])->all();
		 foreach($tmln as $tm) {
		$iter=Iteration::find()->where(['timeline'=>$tm->id,'iteration_type'=>1,'start_date'=>$tm->start_date])->one();
		$ddate=date_format(date_add(date_create($tm->start_date),date_interval_create_from_date_string($tm->duration." days")),"Y-m-d");
		if(!$iter) {
			
			$iter=new Iteration;
			$iter->timeline=$tm->id;
			$iter->iteration_type=1;
			$iter->start_date=$tm->start_date;
			$iter->duration=$tm->duration;
			$iter->end_date=$ddate;
			$iter->save() or die(print_r($iter->gerErrors()));
		}
		
		//Proceed to Submit the Milestone
		$msub=MilestoneSubmission::find()->where(['iteration'=>$iter->id])->one();
		if(!$msub){
			$insert="insert into milestone_submission 
				(`iteration`, `narration`, `status`, `created_at`, `updated_at`, `created_by`, `updated_by`)
				values (
					".$iter->id.",'Submission ',1,'".$ddate."','".$ddate."',2,2
					)";
			Yii::$app->db->createCommand($insert)->execute();
		}
		$msub=MilestoneSubmission::find()->where(['iteration'=>$iter->id])->one();
		if(!$msub) die("failed to insert into mileston submission ".$insert);
	
		// now the indicators
		// get the attached indicators
		
		foreach($sta[$tm->stage] as $ind=>$vs) {
			echo ++$ctr."inserting ".$vs[$tm->milestone]." for indictaor ".$ind." in milestone ".$tm->milestone." stage ".$tm->stage."<br/>";
			$indsub=IndicatorMilestoneSubmission::find()->where(['milestone_submission'=>$msub->id,'indicator'=>$ind])->one();
			if(!$indsub) {
				$insert="insert into indicator_milestone_submission (milestone_submission,indicator,value,created_at,updated_at,created_by,updated_by) values (
				".$msub->id.",".$ind.",'".$vs[$tm->milestone]."','".$ddate."','".$ddate."',2,2)";
				Yii::$app->db->createCommand($insert)->execute();
			}
			$indsub=IndicatorMilestoneSubmission::find()->where(['milestone_submission'=>$msub->id,'indicator'=>$ind])->one();
			if(!$indsub) die("failed to insert indicator sub ".$insert );
			
			//and grade it
			$img=IndicatorGrades::find()->where(['indicator_milestone_submission'=>$indsub->id])->one();
			if(!$img) {
				$img=new IndicatorGrades;
				$img->indicator_milestone_submission=$indsub->id;
				$img->value=$indsub->value;
				$img->save() or die(print_r($img).print_r($img->getErrors())); 
			}	
		}
		//Finally, Grade the milestones
		$mgrd=Grading::find()->where(['milestone_submission'=>$msub->id])->one();
		if(!$mgrd) {
			$insert="insert into grading (milestone_submission,grade,comment,status,created_at,updated_at,created_by,updated_by) values (
			".$msub->id.",1,'System Grade',1,'".$ddate."','".$ddate."',2,2)";
			Yii::$app->db->createCommand($insert)->execute();
			/*$mgrd=new Grading;
			$mgrd->milestone_submission=$msub->id;
			$mgrd->grade=1;
			$mgrd->comment='System Grade';
			$mgrd->status=1;
			$mgrd->save() or die(print_r($mgrd->getErrors()));*/
		}
		$mgrd=Grading::find()->where(['milestone_submission'=>$msub->id])->one();
		if(!$mgrd)
			die("failed to insert grade".$insert);
	}
	 echo "done..";
 }


	 public function actionImport() {
		 
		 	echo "<pre>";	
			
		 //get Milestones Array
		 $ctr=0;
		 $mstones=Yii::$app->db->createCommand("select * from milestone where milestone like 'M00%' order by id asc")->queryAll();
		 //print_r($mstones);
		 //exit;
		 $pri=Yii::$app->db->createCommand("SELECT distinct productname,category from rawdata")->queryAll();
		 $stag=46;
		 $rs=0;
		 foreach($pri as $prod) {
			 echo "action on ".$prod['productname']."<br>";
			 // find Portfolio
			 $po=Program::find()->where(['name'=>$prod['category']])->one();
			 if(!$po) die("po not yet created".$prod['category']);
			 // find or create project
			$pr=Project::find()->where(['name'=>$prod['productname']])->one();
			if(!$pr) {
				$pr=new Project;
				$pr->name = $prod['productname'];
				$pr->innovator=6;
				$pr->program=$po->id;
				$pr->amount=1;
				$pr->institution=2;
				$pr->description=$prod['productname']." for SCMS evaluataion";
				$pr->country=231;
				$pr->teamleader=7;
				$pr->award_date='2011-09-01';
				$pr->signing_date='2011-09-01';
				$pr->startstage=$stag;
				$pr->startmilestone=132;
				$pr->save() or die(print_r($pr->getErrors()));
			}
	
			//find or create timelines
			$ctr=0;
			$data=Rawdata::find()->where(['productname'=>$pr->name])->orderBy(['podate'=>SORT_ASC])->all();
			$rs+=count($data);
			echo count($data)." |".$rs." of ".$pr->name."<br>";
			foreach($data as $r) {
				$projected=$r->projecteddeliverydate ? $r->projecteddeliverydate : $r->deliverydate;
				$duration= round((strtotime($projected) - strtotime($r->podate))/86400);
				$mss=Milestone::find()->where(['milestone'=>$r->podate])->one();
				$mstone=$mss->id;
				$ts=$r->podate;

backend/controllers/TimelineController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Timeline;
use backend\models\TimelineForm;
use backend\models\Milestone;
use backend\models\Item;
use backend\models\Iteration;
use backend\models\IterationSearch;
use backend\models\TimelineSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

use yii\base\Action;
use yii\base\Model;
use yii\bootstrap\ActiveForm;
use yii\web\Response;

/**
 * TimelineController implements the CRUD actions for Timeline model.
 */
class TimelineController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Timeline models.
     * @return mixed
     */
    public function actionIndex($innovation)
    {
        $searchModel = new TimelineSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'innovation'=>$innovation,
        ]);
    }

    /**
     * Displays a single Timeline model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $searchModel = new IterationSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams,$id);

        return $this->render('view', [
            'model' => $this->findModel($id),
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    private function getIterations($timeline){

        $data = Iteration::find()
                ->where(['timeline'=>id])
                ->orderBy('id')
                ->limit(2)
                ->all();
    }

    /**
     * Creates a new Timeline model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {

        $models = $this->getItems();
        $request = Yii::$app->getRequest();
        if ($request->isPost && $request->post('ajax') !== null) {
            $data = Yii::$app->request->post('Item', []);
            foreach (array_keys($data) as $index) {
                $models[$index] = new TimelineForm();
            }
            Model::loadMultiple($models, Yii::$app->request->post());
            Yii::$app->response->format = Response::FORMAT_JSON;
            $result = ActiveForm::validateMultiple($models);
            return $result;
        }

        if (Model::loadMultiple($models, Yii::$app->request->post())) {
            return json_encode($models);
                $model = new TimelineForm();
                if($model->addTimeline($models,Yii::$app->user->identity->id))
                return json_encode("Timelines Added");
        }
        return $this->render('create', [
                'models' => $models,
            ]);
    }

    private function getItems()
    {
        $data = Milestone::find()
                ->orderBy('id')
                ->limit(2)
                ->all();

        $items = [];
        foreach ($data as $row) {
            $item = new TimelineForm();
            $item->setAttributes($row);
            $items[] = $item;
        }
        return $items;
    }

    public function actionIteration($id){
        $model = $this->findModelIteration($id);
        if ($model->load(Yii::$app->request->post())) {
            $sql = 'INSERT INTO iteration (`timeline`,`innovation`,`comment`,`start_date`,`duration`,`created_by`)
                    VALUES ('.$id.','.$model->innovation.',"'.$model->comment.'","'.$model->start_date.'",'.$model->duration.','.Yii::$app->user->identity->id.')';
            if(Yii::$app->db->createCommand($sql)->execute())
            return $this->redirect(['view', 'id' => $id]);
            else
            return $this->render('/iteration/update', [
                'model' => $model,
            ]);
        } else {
            return $this->render('/iteration/update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Timeline model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('updatesingle', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Timeline model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionCalendar($id){
        $data = Iteration::find()
                ->where(['project'=>$id])
                ->orderBy('id')
                ->all();
        $calendardata=array();
        foreach ($data as $data) {
        $calendardata[] =array(
              'title'=> Milestone::findOne(Timeline::findOne($data->timeline)->milestone)->milestone,
              'start'=> $data['start_date'],
              'end' =>date('Y-m-d', strtotime($data['start_date']. ' + '.$data['duration'].' days')),
              'backgroundColor'=> "#f39c12", //yellow
              'borderColor'=> "#f39c12" //yellow
            );
        }
        return $this->render('calendar', [
            'model' => $this->findModel($id),
            'events'=>json_encode($calendardata),
        ]);
    }



    /**
     * Finds the Timeline model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Timeline the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Timeline::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

     /**
     * Finds the Timeline model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Timeline the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModelIteration($id)
    {
        if (($model = Iteration::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/project/timelines/NotificationsController.php
<?php

namespace machour\yii2\notifications\controllers;

use machour\yii2\notifications\models\Notification;
use Yii;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\HttpException;
use yii\web\Response;

class NotificationsController extends Controller
{
    /**
     * @var integer The current user id
     */
    private $user_id;

    /**
     * @var string The notification class
     */
    private $notificationClass;

    /**
     * @inheritdoc
     */
    public function init()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        $this->user_id = $this->module->userId;
        $this->notificationClass = $this->module->notificationClass;
        parent::init();
    }

    /**
     * Poll action
     *
     * @param int $seen Whether to show already seen notifications
     * @return array
     */
    public function actionPoll($seen = 0)
    {
        /** @var Notification $class */
        $class = $this->notificationClass;
        $models = $class::find()->where([
            'user_id' => $this->user_id,
            'end_user'=>1,//1 stands for insititution
            'seen' => $seen
        ])->all();

        $results = [];

      /*  $m=new Notificwion;
        $m->attributes=array(
            'url'=>8888,
            .
            .
            .
            );
        $->getErrors()
        $m->save();
        ""
        */
        foreach ($models as $model) {
            /** @var Notification $model */
            $results[] = [
                'id' => $model->id,
                'type' => $model->type,
                'title' => $model->getTitle(),
                'description' => $model->getDescription(),
                'url' => '/admin2'.$model->url,
                'key' => $model->key,
                'date' => $model->created_at
            ];
        }
        return $results;
    }

    /**
     * Marks a notification as read and redirects the user to the final route
     *
     * @param int $id The notification id
     * @return Response
     * @throws HttpException Throws an exception if the notification is not
     *         found, or if it don't belongs to the logged in user
     */
    public function actionRnr($id)
    {
        $notification = $this->actionRead($id);
        return $this->redirect(Url::to($notification->getRoute()));
    }

    /**
     * Marks a notification as read
     *
     * @param int $id The notification id
     * @return Notification The updated notification record
     * @throws HttpException Throws an exception if the notification is not
     *         found, or if it don't belongs to the logged in user
     */
    public function actionRead($id)
    {
        $notification = $this->getNotification($id);

        $notification->seen = 1;
        $notification->save();

        return $notification;
    }

    /**
     * Deletes a notification
     *
     * @param int $id The notification id
     * @return int|false Returns 1 if the notification was deleted, FALSE otherwise
     * @throws HttpException Throws an exception if the notification is not
     *         found, or if it don't belongs to the logged in user
     */
    public function actionDelete($id)
    {
        $notification = $this->getNotification($id);
        return $notification->delete();
    }


    /**
     * Gets a notification by id
     *
     * @param int $id The notification id
     * @return Notification
     * @throws HttpException Throws an exception if the notification is not
     *         found, or if it don't belongs to the logged in user
     */
    private function getNotification($id)
    {
        /** @var Notification $notification */
        $class = $this->notificationClass;
        $notification = $class::findOne($id);
        if (!$notification) {
            throw new HttpException(404, "Unknown notification");
        }

        if ($notification->user_id != $this->user_id) {
            throw new HttpException(500, "Not your notification");
        }

        return $notification;
    }
}

backend/views/project/timelines/edit_timeline_entry.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\bootstrap\ActiveForm;
use backend\models\Project;
use backend\models\Milestone;
use kartik\date\DatePicker;

/* @var $this yii\web\View */
/* @var $model backend\models\Innovation */

$this->title = 'Update Timeline';
$this->params['breadcrumbs'][] = ['label' => 'Projects', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => 'Timelines', 'url' => ['project/timeline/']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="innovation-update">
<div class="box box-success">
  <div class="box-header bg-success with-border">
                  <h3 class="box-title">Update Timeline for <?=Project::findOne($model->project)->name?></h3>
            </div>
            <div class="box-body">
     <?php $form = ActiveForm::begin(['id' => 'project-form']); ?>
         <?= $form->field($model, 'project',
				['options'=>[
                'tag'=>'div',
                'class'=>'form-group fieldcohort-form-pipeline has-feedback required '],
                'template'=>'{input}{error}{hint}'
                ])->dropDownList(
	ArrayHelper::map(Project::find()->where(['id'=>$model->project])->all(),'id','name'),
	['prompt'=>'Select Project'] )?>
  <?= $form->field($model, 'milestone',
				['options'=>[
                'tag'=>'div',
                'class'=>'form-group fieldcohort-form-pipeline has-feedback required'],
                'template'=>'{input}{error}{hint}'
                ])->dropDownList(
	ArrayHelper::map(Milestone::find()->all(),'id','milestone'),
	['prompt'=>'Select Milestone'] )?>
		<div class="form-group">
      <?= Html::submitButton('Update Timeline Entry', ['class' => 'btn btn-success btn-block btn-flat', 'name' => 'create-button']) ?>
    </div>
<?php ActiveForm::end();?>
</div>
</div>
</div>
    <?= $this->registerJs(
      " 
    $('#project_tree').addClass('active');
    $('#project_nav').addClass('active');")

  ?>

backend/views/project/timelines/project_timeline_view.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
Use yii\helpers\Url;
Use backend\models\Grading;
Use backend\models\MilestoneSubmission;
/* @var $this yii\web\View */
/* @var $searchModel backend\models\TimelineSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Timelines for '.$model->name;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="timeline-index">
<div class="box box-success">
  <div class="box-header bg-success with-border">
                  <h3 class="box-title">Below are the Project <?= Html::encode($this->title) ?>, agreed with the supervisor</h3>
            </div>
            <div class="box-body">
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Calendar View', ['/timeline/calendar','id' => $project], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
             [
             'attribute' => 'Milestone',
             'value' => 'milestone'
             ],
             [
                'label'=>'Start Date',
                'format'=>'raw',
                'value' => function($dataProvider){
                    return date('d-M-Y', strtotime($dataProvider['start_date'])); 
                }
            ],
            [
                'label'=>'Duration (Days)',
                'format'=>'raw',
                'value' => function($dataProvider){
                    return $dataProvider['duration']; 
                }
            ],
            'comment:ntext',
            [
                'label'=>'Status',
                'format'=>'raw',
                'value' => function($dataProvider){
                    $submission = MilestoneSubmission::findOne(['milestone'=>$dataProvider['milestone_id'],'project'=>$dataProvider['project_id']]);
                    if($submission){
                       $grading = Grading::findOne(['milestone'=>$dataProvider['milestone_id'],'project'=>$dataProvider['project_id']]); 
                       if($grading){
                        $grading = Grading::findOne(['milestone'=>$dataProvider['milestone_id'],'status'=>1,'project'=>$dataProvider['project_id']]); 
                        if($grading)
                            return '<i class="fa  fa-check-circle-o"></i> Submission Approved';
                        else
                            return '<i class="fa fa-times-circle"></i> Submission Rejected';
                       }else{
                        return '<i class="fa fa-circle-o"></i> Milestone Submitted but not yet assessed';
                       }

                    }else{
                        return '<i class="fa fa-circle-o"></i> Milestone Not Submitted';
                    }
                }
            ],
            
            // 'start_date',
            // 'created_by',
            // 'created_at',
            // 'updated_at',

            [
            'class' => 'yii\grid\ActionColumn',
            'template' => '{new_action1}{new_action2}{new_action3}',
            'buttons' => [
                'new_action1' => function ($url, $model) {
                    return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', $url, [
                                'title' => Yii::t('app', 'View'),
                    ]);
                }
            ],
            'urlCreator' => function ($action, $model, $key, $index) {
                if ($action === 'new_action1') {
                    $url = Url::to(['project/timeline-entry/'.$model['id'].'']);
                    return $url;
                }
              }
            ],   
            ],
    ]); ?>

</div>
</div>
</div>

backend/views/project/timelines/report.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use backend\models\Milestone;
use yii\widgets\DetailView;

$asset          = common\assets\DatatablesAsset::register($this);
$baseUrl        = $asset->baseUrl;

/* @var $this yii\web\View */
/* @var $model backend\models\Project */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Projects', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = $this->title;
?>
        <style type="text/css">
            table th:first-child {
                width: 150px;
            }
            /* Bootstrap 3.x re-reset */
            .fn-gantt *,
            .fn-gantt *:after,
            .fn-gantt *:before {
              -webkit-box-sizing: content-box;
                 -moz-box-sizing: content-box;
                      box-sizing: content-box;
            }
        </style>

<div class="project-view">
<div class="box box-success">
            <div class="box-body ">
            <h3 class="box-title">Project Summary</h3>
            <div class="chart">
            <?= \common\components\ProjectReport::widget(['project'=>$model->id,]) ?> 
</div>
</div>

</div>